parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: 'mysql://%env(MYSQL_ROOT_PASSWORD)%:%env(MYSQL_ROOT_PASSWORD)%@%env(MYSQL_HOST)%:3306/%env(MYSQL_DATABASE)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Call:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/API/Infrastructure/Persistence/Call'
                prefix: 'App\API\Domain\Model\Call'
                alias: Call
            Elevator:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/API/Infrastructure/Persistence/Elevator'
                prefix: 'App\API\Domain\Model\Elevator'
                alias: Elevator
            Secuence:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/API/Infrastructure/Persistence/Secuence'
                prefix: 'App\API\Domain\Model\Secuence'
                alias: Secuence
